### ISSUE TITLE
game

### ISSUE THREAD

**Issue by manmanrealman** [PolyMarsDev/Terri-Fried#31]
so you know that video you made on how you made the game for 5 consoles in 48 hours? Well I was wanting to know how you made the game for the Wii version step by step. I'm trying to make a homebrew game for Wii called "Call of doody, when you got to go"  and basically its like call of doody but with fart jokes and also its for those people who cant afford cod. Also hears a Wad file for it https://drive.google.com/file/d/1eGS8_dYm9QSp8K5PU-Uui0ceDsSXLLzM/view?usp=sharing also this is supposed to be a joke game. But if you can help me that would be Great

**Comment by BloomyInDev** [comment]
Why it's a wad ? I think it should be an elf or dol. U can't just link the source code ???

**Comment by manmanrealman** [comment]
see the thing is I don't have source code for the WAD :( I'm trying to get help making the dol and elf it self to then be put on a WAD file. U know so like the old times when you download a game for the WII on WII shop then it would have a channel and a game.  I just made the WAD as a test channel, u know like a beta channel. But if you downloaded the WAD on dolphin or Wii then you might have seen the dol I put. But I just need to know how he did it and how the gam was made and how he made the dol and elf file and how he made the game.

**Comment by manmanrealman** [comment]
If u can do that that would be great

**Comment by BloomyInDev** [comment]
> see the thing is I don't have source code for the WAD :( I'm trying to get help making the dol and elf it self to then be put on a WAD file. U know so like the old times when you download a game for the WII on WII shop then it would have a channel and a game. I just made the WAD as a test channel, u know like a beta channel. But if you downloaded the WAD on dolphin or Wii then you might have seen the dol I put. But I just need to know how he did it and how the gam was made and how he made the dol and elf file and how he made the game.

So if u want have help for the elf or dol send them 😃

**Comment by BloomyInDev** [comment]
But before making a wad and installing it on ur wii, make sure that this wad can run on ur wii (NTSC wad don't work on PAL wii or on KOR wii for example, it will brick it essentialy).
There is a reason that the guys behind the homebrew launcher had decided to make a homebrew launcher and not an homebrew installer

**Comment by BloomyInDev** [comment]
And the lib used to make the game is here https://github.com/GRRLIB/GRRLIB

**Comment by manmanrealman** [comment]
alright thanks for the advice, your a life saver man. thanks

**Comment by manmanrealman** [comment]
also instead of using grrlib do u think there's an alterative for python where i can do the same thing polymars did with c++ but instead use python?

**Comment by BloomyInDev** [comment]
Nope i dont think so, but u can search on [google](https://google.com)

**Comment by BloomyInDev** [comment]
But an issue here isn't for how to make a game so please close this issue
